In [1]:
a = {"a": 1, "a":2, "b":2}
a

{'a': 2, 'b': 2}

In [4]:
from natsort import natsorted
a = ['2 ft 7 in', '1 ft 5 in', '10 ft 2 in', '2 ft 11 in', '7 ft 6 in']
b = ['3 ft 3 in', '4 ft 4 in', '7 ft 7 in', '2 ft 2 in']
print(sorted(a))
print(natsorted(a))
print(natsorted(a + b))

['1 ft 5 in', '10 ft 2 in', '2 ft 11 in', '2 ft 7 in', '7 ft 6 in']
['1 ft 5 in', '2 ft 7 in', '2 ft 11 in', '7 ft 6 in', '10 ft 2 in']
['1 ft 5 in', '2 ft 2 in', '2 ft 7 in', '2 ft 11 in', '3 ft 3 in', '4 ft 4 in', '7 ft 6 in', '7 ft 7 in', '10 ft 2 in']


In [6]:
a = {'a': 1}
a = 3
a['a']

TypeError: 'int' object is not subscriptable

In [42]:
import torch
from PIL import Image
import torchvision.transforms as t
import numpy as np
i = torch.zeros(10000).view(100,100).float()
i = i + 100000 
trans = t.ToPILImage()
i = trans(i)
np.array(i).astype( float) 


array([[96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       ...,
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.]])

In [63]:
import numpy as np
i = np.arange(25).reshape(5,5) 
i[None]

a = np.random.randint(2, size=25).reshape(5,5)
b = np.zeros((5,5))
print(a)
print(b)
b[a == 1] = True
print(a)
print(b)

[[0 0 1 1 1]
 [1 1 0 1 0]
 [0 0 0 1 0]
 [0 1 1 0 1]
 [0 0 0 0 1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 1 1 1]
 [1 1 0 1 0]
 [0 0 0 1 0]
 [0 1 1 0 1]
 [0 0 0 0 1]]
[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1.]]
