In [1]:
a = {"a": 1, "a":2, "b":2}
a

{'a': 2, 'b': 2}

In [4]:
from natsort import natsorted
a = ['2 ft 7 in', '1 ft 5 in', '10 ft 2 in', '2 ft 11 in', '7 ft 6 in']
b = ['3 ft 3 in', '4 ft 4 in', '7 ft 7 in', '2 ft 2 in']
print(sorted(a))
print(natsorted(a))
print(natsorted(a + b))

['1 ft 5 in', '10 ft 2 in', '2 ft 11 in', '2 ft 7 in', '7 ft 6 in']
['1 ft 5 in', '2 ft 7 in', '2 ft 11 in', '7 ft 6 in', '10 ft 2 in']
['1 ft 5 in', '2 ft 2 in', '2 ft 7 in', '2 ft 11 in', '3 ft 3 in', '4 ft 4 in', '7 ft 6 in', '7 ft 7 in', '10 ft 2 in']


In [6]:
a = {'a': 1}
a = 3
a['a']

TypeError: 'int' object is not subscriptable

In [42]:
import torch
from PIL import Image
import torchvision.transforms as t
import numpy as np
i = torch.zeros(10000).view(100,100).float()
i = i + 100000 
trans = t.ToPILImage()
i = trans(i)
np.array(i).astype( float) 


array([[96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       ...,
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.],
       [96., 96., 96., ..., 96., 96., 96.]])

In [102]:
import numpy as np
i = np.arange(25).reshape(5,5) 
i[None]

a = np.random.randint(2, size=25).reshape(5,5)
b = np.zeros((5,5))
a = a == 1
b[a] = 5
print(b)
a.size
a.shape

[[5. 5. 5. 5. 0.]
 [0. 5. 5. 5. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 0. 0. 5.]
 [5. 5. 5. 0. 5.]]


(5, 5)

In [96]:
def a():
    print("hahaha")

class b():
    def __init__(self, f):
        self.func = f
    def __call__(self):   
        self.func() 
 
c = b(a)
c()     

hahaha


In [100]:
import torch
a = torch.arange(25).view(5,5)
a.size() , a.shape

(torch.Size([5, 5]), torch.Size([5, 5]))

In [123]:
print(int(1.1))
print(float(1))
print(abs(-1.1))
print(complex(1,1))
print(divmod(13,5))
print(pow(2, 4))

print(bin(128))
print(oct(128))
print(hex(128))

A = [1,2,3,4,5,6,7,8,9]
A[2::5], A[2:5]    
A * 2
list = [i + j for i in range(1,10) for j in range(1,5)] # 다중 for 문 
list = ['pass' if i > 5 else 'fale' for i in range(10)]
list

1
1.0
1.1
(1+1j)
(2, 3)
16
0b10000000
0o200
0x80


['fale',
 'fale',
 'fale',
 'fale',
 'fale',
 'fale',
 'pass',
 'pass',
 'pass',
 'pass']

In [125]:
d = dict(a = 1, b = 2)

for key, value in d.items():
	print(key, value)

a 1
b 2


In [16]:
a = [1,2,3,4,5,6,7,8,9]
a.reverse() 
a


[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [14]:
import torch
a = torch.linspace(0, 5, steps=10 )
a

tensor([0.0000, 0.5556, 1.1111, 1.6667, 2.2222, 2.7778, 3.3333, 3.8889, 4.4444,
        5.0000])

In [2]:
10000** (2 * (2 // 2) / 128)

1.1547819846894583

In [29]:
import torch
a = torch.arange(25).view(1,1,5,5).float()

i = torch.tensor([[[[0,0,0,0],
                    [1,1,1,1],
                    [2,2,2,2]]]],dtype=torch.int64)
out = torch.gather(a, dim = 3, index = i)
out



tensor([[[[ 0.,  0.,  0.,  0.],
          [ 6.,  6.,  6.,  6.],
          [12., 12., 12., 12.]]]])

In [23]:
for i in range(3 , 7):
    print(i)

3
4
5
6


In [31]:
import torch
a = torch.arange(3).view(3,1)
b = torch.arange(3).view(1,3)
(a + b).view(-1)

tensor([0, 1, 2, 1, 2, 3, 2, 3, 4])

In [28]:
import torch
from torch.utils.checkpoint import checkpoint

def a(module):
    def b(*input):
        return module(*input)
    return b 
def module(a, b, c):
    return a * b * c  

c = checkpoint(a(module) , 4,5,6 )

c

/home/bj/data/dnn/torch/lib/python3.10/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")


120

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class m(nn.MultiheadAttention):
    def __init__(self,embed_dim, num_heads):
        super(m, self).__init__(embed_dim,num_heads)
        print( self.in_proj_weight.shape, self.in_proj_weight)

a = m(128, 8)

torch.Size([384, 128]) Parameter containing:
tensor([[ 0.0171,  0.0072,  0.0440,  ...,  0.1018,  0.0539,  0.0040],
        [ 0.0942, -0.0933,  0.0028,  ..., -0.0138, -0.1073, -0.0668],
        [ 0.0943, -0.0954,  0.0177,  ..., -0.0398,  0.1020, -0.0170],
        ...,
        [-0.0367, -0.0678, -0.0327,  ...,  0.0805, -0.0361, -0.0598],
        [-0.0356,  0.1029,  0.0070,  ...,  0.0890, -0.0042, -0.0950],
        [ 0.0682, -0.0097,  0.0280,  ..., -0.0346, -0.1076,  0.0308]],
       requires_grad=True)
